{
 "title": "McServer Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "server", "label": "server", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "core process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "api_server_cpu_usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "elibot_api_server_cpu_usage{instance=~\"$server\",type=\"system\"}"
    }
   ]
  },
  {
   "title": "api_server_mem_rss",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "elibot_api_server_mem_rss{instance=~\"$server\",type=\"system\"}"
    }
   ]
  },
  {
   "title": "mcserver_cpu_usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "elibot_mcserver_cpu_usage{instance=~\"$server\",type=\"system\"}"
    }
   ]
  },
  {
   "title": "mcserver_mem_rss",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "elibot_mcserver_mem_rss{instance=~\"$server\",type=\"system\"}"
    }
   ]
  },
  {
   "title": "cobot_cpu_usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "elibot_cobot_cpu_usage{instance=~\"$server\",type=\"system\"}"
    }
   ]
  },
  {
   "title": "cobot_mem_rss",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "elibot_cobot_mem_rss{instance=~\"$server\",type=\"system\"}"
    }
   ]
  },
  {
   "title": "param_server_cpu_usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "elibot_param_server_cpu_usage{instance=~\"$server\",type=\"system\"}"
    }
   ]
  },
  {
   "title": "param_server_mem_rss",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "elibot_param_server_mem_rss{instance=~\"$server\",type=\"system\"}"
    }
   ]
  },
  { "title": "system", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Server",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "user_cpu_usage_total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 38 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "cpu_usage_user{cpu=\"cpu-total\",instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "mem_used_percent",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 38 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "mem_used_percent{instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "system_load1",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "system_load1{instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "system_load5",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "system_load5{instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "system_load15",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "system_load15{instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "mem_total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 38 },
   "format": "bits",
   "valueName": "current",
   "targets": [
    {
     "expr": "mem_total{instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "mem_vmalloc_total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 40 },
   "format": "bits",
   "valueName": "current",
   "targets": [
    {
     "expr": "mem_vmalloc_total{instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "cobot",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elibot_cobot{instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "api_server",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elibot_api_server{instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "mcserver",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elibot_mcserver{instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "param_server",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elibot_param_server{instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "root_used_percent",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 42 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "disk_used_percent{device=\"rootfs\",fstype=\"rootfs\",instance=~\"$server\",mode=\"rw\",path=\"/\"}"
    }
   ]
  },
  {
   "title": "rbctrl_used_percent",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 42 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "disk_used_percent{device=\"ubi1_0\",fstype=\"ubifs\",instance=~\"$server\",mode=\"rw\",path=\"/rbctrl\"}",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "update_used_percent",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 42 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "disk_used_percent{device=\"ubi2_0\",fstype=\"ubifs\",instance=~\"$server\",mode=\"rw\",path=\"/update\"}",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "disk_used_percent",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 42 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(disk_used{instance=~\"$server\",device=~\"ubi.*\"})/sum(disk_total{instance=~\"$server\",device=~\"ubi.*\"})*100",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "cpu_usage_user",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cpu_usage_user{instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "root_total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 46 },
   "format": "bits",
   "valueName": "current",
   "targets": [
    {
     "expr": "disk_total{device=\"ubi0:rootfs\",fstype=\"ubifs\",instance=~\"$server\",mode=\"ro\",path=\"/\"}"
    }
   ]
  },
  {
   "title": "rbctrl_total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 46 },
   "format": "bits",
   "valueName": "current",
   "targets": [
    {
     "expr": "disk_total{device=\"ubi1_0\",fstype=\"ubifs\",instance=~\"$server\",mode=\"rw\",path=\"/rbctrl\"}"
    }
   ]
  },
  {
   "title": "update_total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 46 },
   "format": "bits",
   "valueName": "current",
   "targets": [
    {
     "expr": "disk_total{device=\"ubi2_0\",fstype=\"ubifs\",instance=~\"$server\",mode=\"rw\",path=\"/update\"}"
    }
   ]
  },
  {
   "title": "disk_total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 46 },
   "format": "bits",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(disk_total{instance=~\"$server\",device=~\"ubi.*\"})"
    }
   ]
  },
  {
   "title": "disk_in_use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "disk_used{instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "mem_used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "mem_used{instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "cpu_usage_system",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cpu_usage_system{instance=~\"$server\"}"
    }
   ]
  }
 ]
}